name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, thank you for your interest in this project, make sure you read the README.md if you're going to work on this. THANK YOU"
        pr-message: "It an absolute pleasure to have you contribute to this project, it will be reviewed and hopefully merged. THANK YOU!"
